# Generated by Django 5.2.7 on 2025-10-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('required_koin_score', models.IntegerField(default=1000)),
            ],
        ),
    ]
